### ISSUE TITLE
Adding Subtypes to an existing Process and enabling Hierarchy

### ISSUE THREAD

**Issue by ICU-Jayaro** [wjohnson/pyapacheatlas#171]
Hi! first of all excellent repo, it has helped us a lot customizing our Purview lineage. I couldn't find a way to post a question and the few tutorials out there do not go this deep (which perhaps is not recommended).

We are trying to get custom processes uploaded in order to provide a better view in the lineage. In other words, not use "Process" but something like the default SubType 'azure_copy_synapse_operation'. We would like to create a Subtype under 'azure_synapse_operation' that provides a more meaningful/specific name than what we have by defaults. Also, we would like to see if there is a way for any Process to have Hierarchy shown in Purview.

I have managed to create a Subtype but it does not show up like a process even though it inherited the attributes from the superType 'azure_synapse_operation'. 

I'm unsure if the following is the problem but I noticed that when I get the entitydef json for 'azure_copy_synapse_operation' and compare it to the new entitydef,

- it has a serviceType (which I can't find how to pass)
- an 'options' (also have not been able to pass in the upload)
- attributedefs is just [].

**Comment by wjohnson** [comment]
Hey, @ICU-Jayaro - Thanks for using the Package!  I apologize for the delay in getting back to you.

Re: Displaying Hierarchy - To my understanding this is is only supported for select types. Custom types do not display hierarchy information unfortunately.

Re: Creating a subtype of an Azure Built-In Type - I would encourage you to avoid doing this mainly because we have no idea where the Purview PG is going to take a type. I wouldn't want to be stuck with whatever attributes they add later on that you would be forced to inherit.

Re: serviceType, options - I'm assuming you're using the PyApacheAtlas SDK for this and not the excel Sheet. I see now that the docstring doesn't list out the kwargs that are available from the BaseTypeDef class ☹

```python

entDef = EntityTypeDef(
name = "typeName",
superTypes = ["Process"],
serviceType = "Something",
options = {"someKey": "someValue" }
)

client.upload_typedefs(entityDefs = [entDef])
```

Are you trying to represent an activity within a Synapse pipeline by any chance?  You have to watch out for Synapse, ADF, and Power BI lineage because they follow a [weird pattern](https://datasmackdown.com/oss/pyapacheatlas/purview/data-factory-lineage.html) of:

* Activity is shown on the lineage graph ([accomplished with options](https://datasmackdown.com/oss/pyapacheatlas/type-options.html))
* Operation is the actual thing that supports lineage

**Comment by ICU-Jayaro** [comment]
Thanks! I imagined it wasn't recommend to go the Subtype route. We just wanted to have a Azure SQL Stored Procedure and try to provide hierarchy to the entity. However, it seems that entity now exists and that in the Private Preview we can get lineage from Stored Procedures (our end goal), so I guess all of this is resolved now. However, there was no mention on how to get access to the private preview.

Since MS is integrating new features continuously, will similar customization features to pyApacheAtlas be available thru the UI in the future? You guys move fast. 

Can we show infrastructure in the Purview UI? It would be neat to show lineage down to the infrastructure level. If so, can we link Sources to Infrastructure?

Are you guys open to collaboration in the repo?

**Comment by wjohnson** [comment]
@ICU-Jayaro you'll need to work with your Microsoft rep on getting access. I am not a member of the product team, just a guy really excited about Atlas and Purview that happens to work at Microsoft.

I can't speak to what the UI will contain in the future but this is something you should definitely convey to your Microsoft account team so that they can help prioritize it with the product group. I'll relay it in my own way but your team will be able to help inform the team even further with the specifics of your use case.

As for Infrastructure, are you speaking explicitly of the Atlas type?  Or are you asking more generically? You can absolutely create a type for, say, and Azure VM and then use relationship attributes to connect the entities together. There isn't a visualization feature for relationship attributes except for the Related tab on custom types.

If you're interested in contributing, I'd love to see what you'd like to share! Most people tend to contribute samples for connectors or explanatory pieces. If you're looking to add something more complex, let's talk it through before you get too far.

**Comment by ICU-Jayaro** [comment]
Thanks again for all the information!
