### ISSUE TITLE
Entity Search - limits ignored - can't pass in "body" 

### ISSUE THREAD

**Issue by nickjacobsen** [wjohnson/pyapacheatlas#184]
So this all pertains to the core/discovery/purview.py (PurviewDiscoveryClient)

**Current desire** 
Search for entities using particular attributes to get a list returned, using either the "body" argument or specifying individual arguments.

All my tests have been using the _search_entities_ method;

With the current code it seems that I cannot pass in a "body" parameter to _search_entities_ and have it work. There is mention on other methods of being able to do this. If that was the intention, I have code to correct that already.

The specifying of a limit  doesn't seem to limit the number of records returned. It seems it return groups at a time, but the client still gets all of the records. This is primary a function of the _search_generator method. Again, I don't know if this is a bug or is intentional and my assumptions are wrong. If the intention is to use the limit to control the API calls but still return everything then it's working as you intended.  

I have some changes to make this perform as I would expect, I just don't know if it is already operating as you intended. 

I'm happy to submit a PR for my changes but want to ensure it's not going against your original intentions.

Regards,
Nick Jacobsen

**Comment by wjohnson** [comment]
Hi, @nickjacobsen - `search_entities` is a general convenience wrapper that tries to make it easier to use the `/query` Purview API without having to implement paging yourself and support existing, older code that was written prior to updating the `PurviewDiscoveryClient` that `PurviewClient` defaults to.

You should be able to pass the same search filter body to the `filter` field. `body` supersedes `keywords` and `filters`.

You are absolutely right, though, I see the gap in `search_entitites`. Normally, you should have been able to pass the `body` parameter and argument as a `kwarg` but I cut it off!  That can definitely be revised. If you already have code written up for it, awesome!  Otherwise, I'm thinking of something like the following in the `_search_generator` method. Pop the known / no side effect kwargs and then pass any along otherwise.  

```
_offset = kwargs.pop("starting_offset") if "starting_offset" in kwargs else 0
_keywords = kwargs.pop("keywords") if "keywords" in kwargs else None
_filter = kwargs.pop("filter") if "filter" in kwargs else None
_facets = kwargs.pop("facets") if "facets" in kwargs else None
_taxonomySetting = kwargs.pop("taxonomySetting") if "taxonomySetting" in kwargs else None
_limit = kwargs.pop("limit") if "limit" in kwargs else 1000

while True:
    results = self.query(
        keywords=_keywords,
        filter=_filter,
        facets=_facets,
        taxonomySetting=_taxonomySetting,
        api_version=kwargs["api_version"],
        limit=_limit,
        offset=_offset,
        **kwargs
    )
```

Lastly, with respect to `limit`, what were your expectations?  If you say "limit=100" do you expect it to only return the top 100 results?  The docstring and the Purview REST API doc say that limit is for the number of results **per page** or per API call. If you set a limit of 100, you will get (at most) 100 results per page and if there are more than 100 results remaining from your offset, you can query the next page by incrementing your offset.

So, "limit" acts on the page level and not on the total number of search results. I hope that helps clarify. Looking forward to any additional feedback or PRs!

**Comment by nickjacobsen** [comment]
Hi @wjohnson, 

Thanks for getting back to me so promptly. I like your idea about popping the known kwargs, that did catch me out, I worked around it a different way. But I'm happy to revisit my code and submit it back as a PR.


When using the `limit` parameter on `search_entities` I would expect to get back that many records. ie If I had set `limit` to 100 I would expect to get 100 records back. Then I can control it with the `starting_offset` to do paging.

When calling `seach_entities` with a `limit` of x, it loops in _search_generator (in pages of `limit` size x), each a separate call to the API,  until no records are returned and then finishes the loop, which seems contrary to what you are saying.

**Comment by wjohnson** [comment]
Re: Limit - If you want to control when you call the next batch, you should
use the query method instead. Search_entities is a convenience wrapper over
query.

If it’s any consolation, since it’s a generator, it still processes one
batch at a time and then calls the query api to fetch the next results
after you’ve completed processing a given batch.

Re: PR, if you felt comfortable sharing, I’d be happy to take a look
enabling the kwargs approach!
