### ISSUE TITLE
Process info

### ISSUE THREAD

**Issue by Vamshi7337** [wjohnson/pyapacheatlas#263]
https://github.com/wjohnson/pyapacheatlas/blob/f5fa20c8042b019b670d32542c068f558ed0d9e9/samples/CRUD/create_entity_and_lineage.py#L57

what if there is no process between two entities and what will be the typeName, qualifiedname and name should be given
@wjohnson

**Comment by wjohnson** [comment]
Hi, @Vamshi7337 ! Thank you for the question. The normal way to do this in Apache Atlas / Microsoft Purview is to include a Process asset between the two objects. In Apache Atlas, you'd normally create some dummy process that just has to sit between the two.

In Microsoft Purview they introduced ["Manual Lineage"](https://learn.microsoft.com/en-us/purview/catalog-lineage-user-guide#manual-lineage) which added a `Sources` and `Sinks` relationship attribute and a trick in the Microsoft Purview Lineage UI (and I believe `/lineage` API) that will render the lineage graph so that a Source appears as an Input to the Sink.

See this sample I provided on [Purview Lineage with No Process](https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/create_lineage_no_process.py) but be warned this is technically undocumented and may change in unexpected ways.
